# Generated by Django 4.2.2 on 2023-07-04 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lodging_app', '0002_lodge_image1_lodge_image2_lodge_image3_lodge_image4'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lodge',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='lodge',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='lodge',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='lodge',
            name='image4',
        ),
    ]
