# Generated by Django 4.2.2 on 2023-07-04 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lodging_app', '0004_lodge_room_chosen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lodge',
            name='is_booked',
        ),
        migrations.RemoveField(
            model_name='lodge',
            name='is_cancelled',
        ),
    ]
