# Generated by Django 4.2.2 on 2023-07-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging_app', '0005_remove_lodge_is_booked_remove_lodge_is_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='lodge',
            name='number_of_people',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
