# Generated by Django 4.2.2 on 2023-07-04 10:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging_app', '0006_lodge_number_of_people'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lodge',
            name='id',
        ),
        migrations.AlterField(
            model_name='lodge',
            name='number_of_people',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
    ]
