# Generated by Django 4.2.2 on 2023-07-04 10:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging_app', '0008_lodge_id_alter_lodge_number_of_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodge',
            name='number_of_people',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
    ]
