# Generated by Django 4.2.2 on 2023-07-04 11:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging_app', '0009_alter_lodge_number_of_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodge',
            name='number_of_people',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(4)]),
        ),
    ]
