# Generated by Django 4.2.3 on 2023-07-09 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lodging_app', '0012_alter_lodge_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lodges', to=settings.AUTH_USER_MODEL),
        ),
    ]
