# Generated by Django 4.2.3 on 2023-07-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging_app', '0013_alter_lodge_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='lodge',
            name='check_in_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lodge',
            name='check_out_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
