# Generated by Django 4.2.3 on 2023-07-14 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lodging_app', '0014_lodge_check_in_date_time_lodge_check_out_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodge',
            name='from_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='lodge',
            name='number_of_people',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lodge',
            name='to_date',
            field=models.DateField(),
        ),
        migrations.AlterModelTable(
            name='lodge',
            table=None,
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lodge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lodging_app.lodge')),
            ],
        ),
    ]
