# Generated by Django 4.2.3 on 2023-07-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging_app', '0015_alter_lodge_from_date_alter_lodge_number_of_people_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lodge',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
