# Generated by Django 4.2.3 on 2023-07-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging_app', '0016_lodge_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lodge',
            name='paid',
        ),
        migrations.AddField(
            model_name='bill',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
