# Generated by Django 4.2.3 on 2023-07-17 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging_app', '0018_invoice_delete_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
