# Generated by Django 4.2.2 on 2023-07-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0004_owner_utility_is_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner_utility',
            name='description',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
