# Generated by Django 4.2.2 on 2023-07-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0006_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp',
            field=models.CharField(blank=True, default='+', max_length=6, null=True),
        ),
    ]
