# Generated by Django 4.2.3 on 2023-07-09 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0008_alter_user_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner_utility',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
