# Generated by Django 4.2.3 on 2023-07-09 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0009_owner_utility_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner_utility',
            name='user',
        ),
    ]
