# Generated by Django 4.2.3 on 2023-07-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0010_remove_owner_utility_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner_utility',
            name='room_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
