---

version: 1

disable_existing_loggers: False

formatters:
    simple:
        format: "%(levelname)s %(asctime)s %(module)s:%(lineno)s %(message)s"
    default:
        format: "%(asctime)s.%(msecs)03d %(levelname)-8s %(name)-15s:%(lineno)s %(message)s"
        datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
    console:
        class: logging.StreamHandler
        level: ERROR
        formatter: default
        stream: ext://sys.stdout
    django_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: default
        filename: django.log
        maxBytes: 10485760 # 10MB
        backupCount: 10
        encoding: utf8
    app_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: default
        filename: restaurants_app.log
        maxBytes: 10485760 # 10MB
        backupCount: 10
        encoding: utf8
    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: default
        filename: errors.log
        maxBytes: 10485760 # 10MB
        backupCount: 10
        encoding: utf8


loggers:
    django:
        handlers: [django_file_handler, error_file_handler]
        level: DEBUG
        propogate: yes
    square_deal_app:
        handlers: [app_file_handler, error_file_handler]
        level: DEBUG
        propogate: yes


root:
    level: ERROR
    handlers: [console]
